name: Deploy Backend

on:
  push:
    branches:
      - main # O la rama en la que quieres desplegar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Build project
        run: npm run build
        working-directory: ./backend

      - name: Start server
        env:
          PORT: ${{ secrets.PORT }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm start
        working-directory: ./backend
